apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-culj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-culj
    app.kubernetes.io/part-of: test-annotations-app-eurs
  name: test-annotations-culj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-culj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-culj
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-ysks-tenant/test-annotations-app-eurs/test-annotations-culj@sha256:06038796c796be4fd0f3855ccec4ae5331c1c4aa72a46b1afd6e097c827bca74
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
